# ***** Telegram TOKEN and parameters Definition *****
TOKEN = "INSERT_TOKEN"
CHANNEL_NAME = "@TELEGRAM_CHANNEL_NAME"

# ***** BOT ACTIVITY TIME *****
MIN_HOUR = 9
MAX_HOUR = 24
PAUSE_MINUTES = 270

# ***** Amazon API Keys and parameters *****
AMAZON_ACCESS_KEY = "AMAZON_ACCESS_KEY"
AMAZON_SECRET_KEY = "AMAZON_SECRET_KEY"
PARTNER_TAG = "AMAZON_PARTNER_TAG"
AMAZON_HOST = "AMAZON_HOST"
AMAZON_REGION = "AMAZON_REGION"

# ***** Bitly API Keys *****
ACCESS_TOKEN = "BITLY_API_KEY"
